main:
  - identifier: about
    name: About
    url: /about
    weight: 1
    post: Our facinating origins
  - identifier: contact
    name: Contact
    url: /contact
    weight: 2
    post: At your service
